import 'dart:math';

class WpConfigService {
  static String generateSalt([int length = 64]) {
    const chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#\$%^&*()-_=+[]{}|;:,.<>?';
    final random = Random.secure();
    return List.generate(length, (_) => chars[random.nextInt(chars.length)]).join();
  }

  static String generateWpConfig({
    required String dbName,
    required String dbUser,
    required String dbPassword,
    required String dbHost,
    String tablePrefix = 'wp_',
    bool debugMode = false,
  }) {
    return '''<?php
/**
 * WordPress Configuration File
 * Generated by WP Launchpad
 *
 * @link https://developer.wordpress.org/advanced-administration/wordpress/wp-config/
 */

// ** Database settings ** //
define( 'DB_NAME', '$dbName' );
define( 'DB_USER', '$dbUser' );
define( 'DB_PASSWORD', '$dbPassword' );
define( 'DB_HOST', '$dbHost' );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

/**
 * Authentication Unique Keys and Salts.
 * Generate new keys at: https://api.wordpress.org/secret-key/1.1/salt/
 */
define( 'AUTH_KEY',         '${generateSalt()}' );
define( 'SECURE_AUTH_KEY',  '${generateSalt()}' );
define( 'LOGGED_IN_KEY',    '${generateSalt()}' );
define( 'NONCE_KEY',        '${generateSalt()}' );
define( 'AUTH_SALT',        '${generateSalt()}' );
define( 'SECURE_AUTH_SALT', '${generateSalt()}' );
define( 'LOGGED_IN_SALT',   '${generateSalt()}' );
define( 'NONCE_SALT',       '${generateSalt()}' );

/**
 * WordPress Database Table prefix.
 */
\$table_prefix = '$tablePrefix';

/**
 * Debugging mode.
 */
define( 'WP_DEBUG', ${debugMode ? 'true' : 'false'} );
${debugMode ? "define( 'WP_DEBUG_LOG', true );\ndefine( 'WP_DEBUG_DISPLAY', false );" : ''}

/* Add any custom values between this line and the "stop editing" line. */

/* That's all, stop editing! Happy publishing. */

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', __DIR__ . '/' );
}

/** Sets up WordPress vars and included files. */
require_once ABSPATH . 'wp-settings.php';
''';
  }
}
